name: musicscool
description: Mobile app for Music'scool students.

publish_to: 'none' # Do not publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.1.1
  scrollable_positioned_list: ^0.1.8
  intl: ^0.16.1
  provider: ^4.3.2+3
  url_launcher: ^5.7.10
  flutter_secure_storage: ^3.3.5
  flutter_svg: ^0.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^1.1.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  test: any
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  main_locale: en_US
  enabled: true
