name: musicscool
description: Mobile app for Music'scool students.

publish_to: 'none' # Do not publish to pub.dev

version: 1.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  infinite_scroll_pagination: ^2.2.3
  json_annotation: ^3.1.1
  intl: ^0.16.1
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  provider: ^4.3.2+3
  get_it: ^5.0.3
  url_launcher: ^5.7.10
  path_provider: ^1.6.24
  open_file: ^3.0.3
  permission_handler: ^5.1.0+2
  flutter_local_notifications: ^3.0.2
  timezone: ^0.5.9
  flutter_native_timezone: ^1.0.4
  flutter_secure_storage: ^3.3.5
  flutter_svg: ^0.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^1.1.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  test: any
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  main_locale: en_US
  enabled: true
