name: musicscool
description: Mobile app for Music'scool students.

publish_to: 'none' # Do not publish to pub.dev

version: 1.2.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  package_info_plus: ^3.0.2
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.0.1
  intl: ^0.17.0
  table_calendar: ^3.0.5
  dio: ^4.0.4
  dio_http_cache_lts: ^0.4.1
  provider: ^6.0.2
  get_it: ^7.2.0
  url_launcher: ^6.1.6
  path_provider: ^2.0.0
  open_filex: ^4.1.1
  permission_handler: ^10.1.0
  flutter_local_notifications: ^12.0.2
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.4
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_messaging: ^14.1.4

dev_dependencies:
  test: any
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  main_locale: en_US
  enabled: true
