name: musicscool
description: Mobile app for Music'Scool students.

publish_to: 'none' # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: '>=0.5.0 <2.0.0'  # Temporary
  json_annotation: ^3.1.1
  url_launcher: ^5.7.10
  flutter_svg: ^0.19.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  test: any
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
