name: musicscool
description: Mobile app for Music'scool students.

publish_to: 'none' # Do not publish to pub.dev

version: 1.2.8

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  package_info_plus: ^8.3.0
  sliver_tools: ^0.2.12
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.0.1
  intl: ^0.19.0
  table_calendar: ^3.0.5
  dio: ^4.0.4
  dio_http_cache_lts: ^0.4.1
  provider: ^6.0.2
  get_it: ^7.2.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  open_filex: ^4.1.1
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.0
  flutter_timezone: ^2.1.0
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.4
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4

dev_dependencies:
  test: any
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
  http: any
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  main_locale: en_US
  enabled: true
